[package]
name = "eqsat-ai"
version = "0.1.0"
edition = "2024"

[lib]
name = "eqsat_ai"
path = "src/lib.rs"

[[bin]]
name = "experiment"

[dependencies]
clap = { version = "*", features = ["derive"] }
lalrpop-util = { version = "*", features = ["lexer", "unicode"] }
symbol_table = { version = "*", features = ["global", "serde"] }

[build-dependencies]
lalrpop = "*"
compile-rw = { path = "../compile-rw" }
