[package]
name = "eqsat-ai"
version = "0.1.0"
edition = "2024"

[lib]
name = "eqsat_ai"
path = "src/lib.rs"

[[bin]]
name = "experiment"

[dependencies]
derive_more = { version = "*", features = ["from_str"] }
hashbrown = "*"
lalrpop-util = { version = "*", features = ["lexer", "unicode"] }
symbol_table = { version = "*", features = ["global"] }

[build-dependencies]
lalrpop = "*"
