[package]
name = "eqsat-ai"
version = "0.1.0"
edition = "2024"

[lib]
name = "eqsat_ai"
path = "src/lib.rs"

[[bin]]
name = "experiment"

[dependencies]
clap = { version = "*", features = ["derive"] }
derive_more = { version = "*", features = ["from_str"] }
hashbrown = "*"
lalrpop-util = { version = "*", features = ["lexer", "unicode"] }
serde = { version = "*", features = ["derive"] }
spytial = "*"
symbol_table = { version = "*", features = ["global", "serde"] }

[build-dependencies]
lalrpop = "*"
