use core::str::FromStr;

use symbol_table::GlobalSymbol as Symbol;

use crate::{Literal, Pattern, Rule, Type};

grammar();

pub Rules: Vec<Rule> = {
    Rule* => <>,
}

Rule: Rule = {
    "(" "rw" <mut lhs:Pattern> <rhs:Pattern> ")" => {
        let root_lhs = lhs.label_mut();
        let label = match root_lhs {
            Some(label) => *label,
            None => {
                 let label = "_root_lhs".into();
                 *root_lhs = Some(label);
                 label
            }
        };
        let rhs = Pattern::Union(Box::new(Pattern::Variable(label)), Box::new(rhs));
        Rule { lhs: vec![lhs], cond: None, rhs: vec![rhs] }
    },
    "(" "rule" "(" <lhs:Pattern*> ")" "(" <rhs:Pattern*> ")" ")" => Rule { lhs, cond: None, rhs },
    "(" "rule" "(" <lhs:Pattern*> ")" <cond:RustExpr> "(" <rhs:Pattern*> ")" ")" => Rule { lhs, cond: Some(cond), rhs },
}

Pattern: Pattern = {
    "contradiction" => Pattern::Contradiction,
    Iden => Pattern::Variable(<>),
    Num => Pattern::Literal(Literal::I64(<>)),
    Bool => Pattern::Literal(Literal::Bool(<>)),
    RustExpr => Pattern::RustExpr(<>),
    "(" "union" <lhs:Pattern> <rhs:Pattern> ")" => Pattern::Union(Box::new(lhs), Box::new(rhs)),
    "_" => Pattern::Wildcard,
    "(" "Constant" "[" <ty:Type> "]" <cons:Pattern> ")" => Pattern::Constant { ty, input: Box::new(cons), label: None },
    "(" "Param" "[" <ty:Type> "]" <idx:Pattern> ")" => Pattern::Param { ty, idx: Box::new(idx), label: None },
    "(" <op:Iden> <inp:Pattern> ")" => Pattern::Unary { op, input: Box::new(inp), label: None },
    "(" <op:Iden> <lhs:Pattern> <rhs:Pattern> ")" => Pattern::Binary { op, lhs: Box::new(lhs), rhs: Box::new(rhs), label: None },
    "(" "Knot" "[" <ty:Type> "]" <kb:Pattern> <int:Pattern> <knot_id:Pattern> ")" => Pattern::Knot { ty, kb: Box::new(kb), int: Box::new(int), knot_id: Box::new(knot_id), label: None },
    "(" "KnownBits" <id:Pattern> <kb:Pattern> ")" => Pattern::KnownBits { id: Box::new(id), kb: Box::new(kb) },
    "(" "Interval" <id:Pattern> <int:Pattern> ")" => Pattern::Interval { id: Box::new(id), int: Box::new(int) },
    <label:Iden> ":" "(" "Constant" "[" <ty:Type> "]" <cons:Pattern> ")" => Pattern::Constant { ty, input: Box::new(cons), label: Some(label) },
    <label:Iden> ":" "(" "Param" "[" <ty:Type> "]" <idx:Pattern> ")" => Pattern::Param { ty, idx: Box::new(idx), label: Some(label) },
    <label:Iden> ":" "(" <op:Iden> <inp:Pattern> ")" => Pattern::Unary { op, input: Box::new(inp), label: Some(label) },
    <label:Iden> ":" "(" <op:Iden> <lhs:Pattern> <rhs:Pattern> ")" => Pattern::Binary { op, lhs: Box::new(lhs), rhs: Box::new(rhs), label: Some(label) },
    <label:Iden> ":" "(" "Knot" "[" <ty:Type> "]" <kb:Pattern> <int:Pattern> <knot_id:Pattern> ")" => Pattern::Knot { ty, kb: Box::new(kb), int: Box::new(int), knot_id: Box::new(knot_id), label: Some(label) },
}

Type: Type = {
    "i64" => Type::I64,
    "bool" => Type::Bool,
}

Iden: Symbol = r"[a-zA-Z][a-zA-Z0-9_]*" => Symbol::from(<>);
Num: i64 = r"-?[0-9]+" => i64::from_str(<>).unwrap();
Bool: bool = {
    "false" => false,
    "true" => true,
}
RustExpr: Symbol = <re:r#"`(\\\\|\\`|[^`\\])*`"#> => re[1..re.len() - 1].into();
