use core::str::FromStr;

use symbol_table::GlobalSymbol as Symbol;

use crate::{Literal, Pattern, Rewrite, Type};

grammar();

pub Rewrites: Vec<Rewrite> = {
    Rewrite* => <>,
}

Rewrite: Rewrite = {
    "(" "rw" <lhs:Pattern> <rhs:Pattern> ")" => Rewrite { lhs, rhs },
}

Pattern: Pattern = {
    Iden => Pattern::Variable(<>),
    Num => Pattern::Literal(Literal::I64(<>)),
    Bool => Pattern::Literal(Literal::Bool(<>)),
    RustExpr => Pattern::RustExpr(<>),
    "_" => Pattern::Wildcard,
    "(" "Constant" "[" <ty:Type> "]" <cons:Pattern> ")" => Pattern::Constant { ty, input: Box::new(cons) },
    "(" <op:Iden> <inp:Pattern> ")" => Pattern::Unary { op, input: Box::new(inp) },
    "(" <op:Iden> <lhs:Pattern> <rhs:Pattern> ")" => Pattern::Binary { op, lhs: Box::new(lhs), rhs: Box::new(rhs) },
}

Type: Type = {
    "i64" => Type::I64,
    "bool" => Type::Bool,
}

Iden: Symbol = r"[a-zA-Z][a-zA-Z0-9_]*" => Symbol::from(<>);
Num: i64 = r"-?[0-9]+" => i64::from_str(<>).unwrap();
Bool: bool = {
    "false" => false,
    "true" => true,
}
RustExpr: Symbol = <re:r#"`(\\\\|\\`|[^`\\])*`"#> => re[1..re.len() - 1].into();

List<T>: Vec<T> = {
    <mut v:(<T> ",")*> <e:T?> => match e {
        None => v,
        Some(e) => {
            v.push(e);
            v
        }
    }
};
