[package]
name = "compile-rw"
version = "0.1.0"
edition = "2024"

[lib]
name = "compile_rw"
path = "src/lib.rs"

[dependencies]
hashbrown = "*"
lalrpop-util = { version = "*", features = ["lexer", "unicode"] }
prettyplease = "*"
proc-macro2 = "*"
quote = "*"
symbol_table = { version = "*", features = ["global", "serde"] }
syn = "*"

[build-dependencies]
lalrpop = "*"
